version: '3'
services:
  ec2:
    build:
        context: .
        dockerfile: ./docker/dev/amazonlinux/Dockerfile
    image: ec2-app:latest
    #restart: always
    container_name: 'ec2-app'
    working_dir: '/home/ec2-user/'
    tty: true
    env_file: .env
    entrypoint: bash -c 'sh /tmp/userdata.sh; bash'
    #volumes:
    #  - ./src:/usr/src