version: '3'
services:
  ec2:
    build:
        context: .
        dockerfile: ./docker/dev/amazonlinux/Dockerfile
    image: ec2-app:latest
    container_name: 'ec2-app'
    working_dir: '/home/ec2-user/'
    tty: true
    env_file: .env
    entrypoint: >
        bash -c 'APP_ENV=local bash /tmp/userdata.sh && \
                 source .bash_profile && \
                 bash'
    volumes:
      - ./src:/home/ec2-user/crawler/src